video_processing:
  input_video_dir: data/raw/original/
  output_video_dir: data/raw/reduced/
  reduction_factor: 4

labeling:
  labels:
    m: meathook
    n: nutcracker
    l: l-hang
    o: other pose or transition
    r: reverse meathook
    b: back lever
    f: front lever
  skip_frames: 60
  input_video_dir: data/raw/reduced/
  output_dir: data/interim/