video_processing:
  input_video_dir: data/raw/original/
  output_video_dir: data/interim/reduced/
  reduction_factor: 4

labeling:
  labels:
    m: meathook
    n: nutcracker
    l: l-hang
    o: other pose or transition
    r: reverse meathook
    b: back lever
    f: front lever
  skip_frames: 60
  input_video_dir: data/interim/reduced/
  output_dir: data/interim/labeled/

features:
  input_video_dir: data/interim/reduced/
  output_video_dir: data/processed/videos/
  interim_features_directory: data/interim/features
  labeled_dir: data/interim/labeled
  write_video: False
  final_features_directory: data/processed/features

model:
  model_type: xgb
  final_features_filepath: data/processed/features/final_features.csv
  test_size: 0.3
  target_column: label
  predictions_dir: data/results/
  optimize_hyperparams: False

